// import { NextResponse } from "next/server";

// const Products = [
//         {
//             id:1,
//             image: "/image/Rectangle.png",
//             label: "Just In",
//             title: "Nike Air Force 1 Mid '07",
//             category: "Men's Shoes",
//             color: "1 Color",
//             price: "10795.00",
//         },
//         {   
//             id:2,
//             image: "/image/Rectangle (1).png",
//             label: "Just In",
//             title: "Nike Court Vision Low Next Nature",
//             category: "Men's Shoes",
//             color: "1 Colors",
//             price: "4995.00",
//         },
//         {
//             id:3,
//             image: "/image/Rectangle (2).png",
//             label: "Just In",
//             title: "Nike Air Force 1 PLT.AF.ORM",
//             category: "Women's Shoes",
//             color: "3 Colors",
//             price: "8695.00",
//         },
//         {
//             id:4,
//             image: "/image/Rectangle (3).png",
//             label: "Just In",
//             title: "Nike Air Force 1 React",
//             category: "Men's Shoes",
//             color: "1 Color",
//             price: "13295.00",
//         },
//         {
//             id:5,
//             image: "/image/Rectangle (4).png",
//             label: "Promo Exclusion",
//             title: "Air Jordan 1 Elevate Low",
//             category: "Women's Shoes",
//             color: "1 Color",
//             price: "11895.00",
//         },
//         {
//             id:6,
//             image: "/image/Rectangle (5).png",
//             label: "Just In",
//             title: "Nike Standard Issue",
//             category: "Women's Shoes",
//             color: "1 Color",
//             price: "2895.00",
//         },
//         {
//             id:7,
//             image: "/image/Rectangle (6).png",
//             label: "Promo Exclusion",
//             title: "Nike Dunk Low Retro SE",
//             category: "Men's Shoes",
//             color: "1 Color",
//             price: "9695.00",
//         },
//         {
//             id:8,
//             image: "/image/Rectangle (7).png",
//             label: "Sustainable Materials",
//             title: "Nike Dri-FIT UV Hyverse",
//             category: "Men's Short-Sleeve Graphic Fitness Top",
//             color: "1 Color",
//             price: "2495.00",
//         },
//         {
//             id:9,
//             image: "/image/Rectangle (8).png",
//             label: "Just In",
//             title: "Nike Court Vision Low",
//             category: "Men's Shoes",
//             color: "1 Color",
//             price: "5695.00",
//         },
//         {
//             id:10,
//             image: "/image/Rectangle (9).png",
//             label: "Just In",
//             title: "Nike Dri-FIT Ready",
//             category: "Men's Short-Sleeve Graphic Fitness Top",
//             color: "1 Color",
//             price: "2495.00",
//         },
//         {
//             id:11,
//             image: "/image/Rectangle (10).png",
//             label: "Just In",
//             title: "Nike One Leak Protection: Period",
//             category: "Women's Mid-Rise 18cm (approx.) Biker Shorts",
//             color: "2 Color",
//             price: "3395.00",
//         },
//         {
//             id:12,
//             image: "/image/Rectangle (11).png",
//             label: "Just In",
//             title: "Nike Force 1 LV8 3",
//             category: "Older Kids' Shoes",
//             color: "1 Color",
//             price: "7495.00",
//         },
//         {
//             id:13,
//             image: "/image/Rectangle (12).png",
//             label: "Just In",
//             title: "Nike Blazer Low Platform",
//             category: "Women's Shoes",
//             color: "1 Color",
//             price: "8195.00",
//         },
//         {
//             id:14,
//             image: "/image/Rectangle (13).png",
//             label: "Just In",
//             title: "Nike Blazer Low Platform",
//             category: "Women's Shoes",
//             color: "1 Color",
//             price: "8195.00",
//         },
//         {
//             id:15,
//             image: "/image/Rectangle (14).png",
//             label: "Just In",
//             title: "Nike Pro Dri-FIT",
//             category: "Men's Short-Sleeve Graphic Fitness Top",
//             color: "1 Color",
//             price: "1495.00",
//         },
//         {
//             id:16,
//             image: "/image/Rectangle (15).png",
//             label: "Just In",
//             title: "Nike Dunk Low Retro",
//             category: "Men's Shoes",
//             color: "1 Color",
//             price: "8695.00",
//         },
//         {
//             id:17,
//             image: "/image/Rectangle (16).png",
//             label: "Just In",
//             title: "Nike Air Max SC",
//             category: "Women's Shoes",
//             color: "2 Color",
//             price: "5995.00",
//         },
//         {
//             id:18,
//             image: "/image/Rectangle (17).png",
//             label: "Just In",
//             title: "Nike Dri-FIT UV Miler",
//             category: "Men's Shorts-Sleeve Running Top",
//             color: "1 Color",
//             price: "1695.00",
//         },
//         {
//             id:19,
//             image: "/image/Rectangle (18).png",
//             label: "Just In",
//             title: "Nike Air Max SYSTEM",
//             category: "Older Kids' Shoes",
//             color: "1 Color",
//             price: "6495.00",
//         },
//         {
//             id:20,
//             image: "/image/Rectangle (19).png",
//             label: "Just In",
//             title: "Nike Alate AI U",
//             category: "women's Light-Support Lightly Lined U-Neck Printed Sports Bra",
//             color: "1 Color",
//             price: "2195.00",
//         },
//         {
//             id:21,
//             image: "/image/Rectangle (20).png",
//             label: "Just In",
//             title: "Nike Court Legacy Lift",
//             category: "Women's Shoes",
//             color: "2 Color",
//             price: "7495.00",
//         },
//         {
//             id:22,
//             image: "/image/Rectangle (21).png",
//             label: "Just In",
//             title: "Nike Swoosh",
//             category: "Women's Medium-support Padded Sports Bra Tank",
//             color: "2 Color",
//             price: "3095.00",
//         },
//         {
//             id:23,
//             image: "/image/Rectangle (22).png",
//             label: "Just In",
//             title: "Nike SB Zoom Janoski OG+",
//             category: "Shoes",
//             color: "1 Color",
//             price: "8595.00",
//         },
//         {
//             id:24,
//             image: "/image/Rectangle (23).png",
//             label: "Just In",
//             title: "Nike Dri-FIT Run Division Rise 365",
//             category: "Men's Running Tank",
//             color: "2 Color",
//             price: "3495.00",
//         },
//         {
//             id:25,
//             image: "/image/Rectangle (24).png",
//             label: "Just In",
//             title: "Nike Dri-FIT Challenger",
//             category: "Men's 18cm (approx) 2-in-1 Versatile Shorts",
//             color: "1 Color",
//             price: "2495.00",
//         },
//         {
//             id:26,
//             image: "/image/Rectangle (25).png",
//             label: "Just In",
//             title: "Jordan Series ES",
//             category: "Men's Shoes",
//             color: "2 Color",
//             price: "7495.00",
//         },
//         {
//             id:27,
//             image: "/image/Rectangle (26).png",
//             label: "Just In",
//             title: "Nike Outdoor Play",
//             category: "Older kids' Oversized Woven Jacket",
//             color: "1 Color",
//             price: "3895.00",
//         },
//         {
//             id:28,
//             image: "/image/Rectangle (27).png",
//             label: "Just In",
//             title: "Nike Sportswear Trend",
//             category: "Older Kids' (Girls') High-wasted Woven Shorts",
//             color: "2 Color",
//             price: "2495.00",
//         },
//         {
//             id:29,
//             image: "/image/Rectangle (28).png",
//             label: "Just In",
//             title: "Nike Blazer Low '77 Jumbo",
//             category: "Women's Shoes",
//             color: "1 Color",
//             price: "8595.00",
//         },
//         {
//             id:30,
//             image: "/image/Rectangle (29).png",
//             label: "Just In",
//             title: "Nike SB Force 58",
//             category: "Skate Shoe",
//             color: "1 Color",
//             price: "5995.00",
//         },
// ];

// export async function GET() {
//   return NextResponse.json(Products);
// }

